FROM mcr.microsoft.com/dotnet/sdk:3.1 as build 
WORKDIR /app

COPY ./ExchangeRates.Processor.csproj ./
RUN dotnet restore

COPY ./ ./
RUN dotnet publish -o out 

FROM mcr.microsoft.com/dotnet/runtime:3.1 as runtime
WORKDIR /app

COPY --from=build /app/out .
ENTRYPOINT ["dotnet","ExchangeRates.Processor.dll"]

