FROM  mcr.microsoft.com/dotnet/sdk:3.1 as allbuilds
workdir /app


RUN mkdir DockerExample.App
RUN mkdir DockerExample.Test

COPY DockerExample.sln ./

COPY DockerExample.App/*.csproj DockerExample.App
COPY DockerExample.Test/*.csproj DockerExample.Test

RUN dotnet restore 

COPY ./ ./
RUN dotnet build 
RUN dotnet publish -o ./out -c Release
COPY ps.ps1 /

FROM mcr.microsoft.com/dotnet/runtime:3.1 
WORKDIR /app

COPY --from=allbuilds /app/out .
ENTRYPOINT ["dotnet", "DockerExample.App.dll"]
